<script src="<%=basePath%>static/plugins/jQuery/jquery-2.2.3.min.js"></script>
<script src="<%=basePath%>static/plugins/jQueryUI/jquery-ui.min.js"></script>
<script src="<%=basePath%>static/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="<%=basePath%>static/plugins/raphael/raphael-min.js"></script>
<script src="<%=basePath%>static/plugins/morris/morris.min.js"></script>
<script src="<%=basePath%>static/plugins/sparkline/jquery.sparkline.min.js"></script>
<script src="<%=basePath%>static/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
<script src="<%=basePath%>static/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
<script src="<%=basePath%>static/plugins/knob/jquery.knob.js"></script>
<%--<script src="<%=basePath%>static/plugins/daterangepicker/moment.min.js"></script>--%>
<%--<script src="<%=basePath%>static/plugins/daterangepicker/daterangepicker.js"></script>--%>
<%--<script src="<%=basePath%>static/plugins/daterangepicker/daterangepicker.zh-CN.js"></script>--%>
<script src="<%=basePath%>static/plugins/datepicker/bootstrap-datepicker.js"></script>
<script src="<%=basePath%>static/plugins/datepicker/locales/bootstrap-datepicker.zh-CN.js"></script>
<script src="<%=basePath%>static/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
<script src="<%=basePath%>static/plugins/slimScroll/jquery.slimscroll.min.js"></script>
<script src="<%=basePath%>static/plugins/fastclick/fastclick.js"></script>
<script src="<%=basePath%>static/plugins/iCheck/icheck.min.js"></script>
<script src="<%=basePath%>static/plugins/adminLTE/js/app.min.js"></script>
<script src="<%=basePath%>static/plugins/treeTable/jquery.treetable.js"></script>
<script src="<%=basePath%>static/plugins/select2/select2.full.min.js"></script>
<script src="<%=basePath%>static/plugins/colorpicker/bootstrap-colorpicker.min.js"></script>
<script src="<%=basePath%>static/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.zh-CN.js"></script>
<script src="<%=basePath%>static/plugins/bootstrap-markdown/js/bootstrap-markdown.js"></script>
<script src="<%=basePath%>static/plugins/bootstrap-markdown/locale/bootstrap-markdown.zh.js"></script>
<script src="<%=basePath%>static/plugins/bootstrap-markdown/js/markdown.js"></script>
<script src="<%=basePath%>static/plugins/bootstrap-markdown/js/to-markdown.js"></script>
<script src="<%=basePath%>static/plugins/ckeditor/ckeditor.js"></script>
<script src="<%=basePath%>static/plugins/input-mask/jquery.inputmask.js"></script>
<script src="<%=basePath%>static/plugins/input-mask/jquery.inputmask.date.extensions.js"></script>
<script src="<%=basePath%>static/plugins/input-mask/jquery.inputmask.extensions.js"></script>
<script src="<%=basePath%>static/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="<%=basePath%>static/plugins/datatables/dataTables.bootstrap.min.js"></script>
<script src="<%=basePath%>static/plugins/chartjs/Chart.min.js"></script>
<script src="<%=basePath%>static/plugins/flot/jquery.flot.min.js"></script>
<script src="<%=basePath%>static/plugins/flot/jquery.flot.resize.min.js"></script>
<script src="<%=basePath%>static/plugins/flot/jquery.flot.pie.min.js"></script>
<script src="<%=basePath%>static/plugins/flot/jquery.flot.categories.min.js"></script>
<script src="<%=basePath%>static/plugins/ionslider/ion.rangeSlider.min.js"></script>
<script src="<%=basePath%>static/plugins/bootstrap-slider/bootstrap-slider.js"></script>
<script src="<%=basePath%>static/plugins/bootstrap-datetimepicker/bootstrap-datetimepicker.js"></script>
<script src="<%=basePath%>static/plugins/bootstrap-datetimepicker/locales/bootstrap-datetimepicker.zh-CN.js"></script>
<%--后面添加的--%>
<%--对话框--%>
<script src="<%=basePath%>static/plugins/assets/ast-notif.js"></script>
<script src="<%=basePath%>static/plugins/assets/message.js"></script>
<%--选择题--%>
